# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "arret"
    dynamodb_table = "terra-lock-table"
    encrypt        = true
    key            = "organizations/terraform.tfstate"
    region         = "us-east-1"
  }
}
